version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: calendar-postgres-prod
    environment:
      POSTGRES_USER: ${DB_USER:-calendar_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-calendar_password}
      POSTGRES_DB: ${DB_NAME:-calendar_db}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calendar-network-prod
    restart: unless-stopped

  backend:
    image: sim31906/calendar-backend:latest
    container_name: calendar-backend-prod
    environment:
      PORT: 5001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-calendar_user}
      DB_PASSWORD: ${DB_PASSWORD:-calendar_password}
      DB_NAME: ${DB_NAME:-calendar_db}
      NODE_ENV: production
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - calendar-network-prod
    restart: unless-stopped

  frontend:
    image: sim31906/calendar-frontend:latest
    container_name: calendar-frontend-prod
    ports:
      - "6016:6016"
    depends_on:
      - backend
    networks:
      - calendar-network-prod
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  calendar-network-prod:
    driver: bridge