name: Deploy to Docker Hub

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.sim31906 }}
          password: ${{ secrets.docker31906 }}

      - name: Build and Push Frontend
        run: |
          docker build -t sim31906/calendar-frontend frontend/
          docker push sim31906/calendar-frontend
