name: Deploy to Docker Hub

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/calendar-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/calendar-backend:latest

      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/calendar-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/calendar-frontend:latest
